---
# Automatic building in CI

name: Build / test

on:
  push:
  pull_request:
    branches: [main]
jobs:
  cmake:
    name: Build and test
    runs-on: ubuntu-22.04
    steps:
      - name: checkout source
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install analysis tools
        run: |
          sudo apt update
          sudo apt install -y valgrind
      - name: configure
        run: >
          cmake
          -B build
          -Werror=dev
          ${{ runner.os != 'Windows' && '-DCMAKE_BUILD_TYPE=Debug' || '' }}
      - name: make
        run: cmake --build build --config Debug --verbose
      - name: make check
        run: >
          ctest
          --test-dir build
          --parallel 2
          --output-on-failure
          --no-tests=error
          --build-config Debug
          -VV
      - name: valgrind check
        run: >
          ctest
          -T MemCheck
          --test-dir build
          --parallel 2
          --output-on-failure
          --no-tests=error
          --build-config Debug
          -VV
