---
# https://github.com/marketplace/actions/c-c-linter

name: clang-tidy-review
on: [pull_request]

jobs:
  clang-tidy-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cmake
        run: >
          CC=clang cmake
          -G "Unix Makefiles"
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_EXPORT_COMPILE_COMMANDS=on .
      - uses: cpp-linter/cpp-linter-action@v2
        id: review
        with:
          style: file
          lines-changed-only: true
          database: .
          tidy-checks: >-
            bugprone-*,
            performance-*,
            readability-*,
            portability-*,
            modernize-*,
            clang-analyzer-*
      - name: Fail fast?!
        if: steps.review.outputs.checks-failed > 0
        run: |
          echo "Some files failed the linting checks!"
