---
# https://github.com/marketplace/actions/clang-tidy-review

name: clang-tidy-review
on: [pull_request]

jobs:
  clang-tidy-review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ZedThree/clang-tidy-review@v0.10.1
      id: review
      with:
        # CMake command to run in order to generate compile_commands.json
        cmake_command: >
          cmake
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_EXPORT_COMPILE_COMMANDS=on .
