---
# Automatic building in CI

name: Build / Codecov

on:
  push:
  pull_request:
    branches: [main]
jobs:
  cmake:
    name: Build and coverage
    runs-on: ubuntu-22.04
    steps:
      - name: checkout source
        uses: actions/checkout@v3
      - name: setup gcov flags
        run: |
          echo "CFLAGS=-fprofile-arcs -ftest-coverage" >> "$GITHUB_ENV"
      - name: configure
        run: >
          cmake
          -B build
          -Werror=dev
          ${{ runner.os != 'Windows' && '-DCMAKE_BUILD_TYPE=Debug' || '' }}
      - name: make
        run: cmake --build build --config Debug --verbose
      - name: Generate coverage report
        run: >
          ctest
          --test-dir build
          --parallel 2
          --output-on-failure
          --no-tests=error
          --build-config Debug
          -VV
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          gcov: true
          gcov_ignore: tests
